from .main import register_admin_cogs
from .find import register_find_cogs
from .moderation import register_moderation_cogs
from .ssh import register_SSH_cogs
from .database import register_database_cogs
from .bot import register_bot_cogs
from .accounts import register_accounts_cogs
from .admin_discipline import register_admin_discipline_cogs
from .elections import register_elections_cogs
from .server import register_server_cogs
from .promo import register_promo_cogs
