from .database_ping import register_ping_databases_cogs
from .players import register_players_task_cogs
from .status import register_status_task_cogs
from .admin_discipline_table import register_admin_discipline_table_cogs
from .register_log import register_register_log_cogs
